FROM python:3.12-slim

COPY . /app
# Set the working directory
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl procps && \
    pip install uv --no-cache-dir

# Expose port 5000 for FastAPI
EXPOSE 5000

# Run the app
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]