apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: coelho-realtime

build:
  artifacts:
    # Kafka Producers (Python data generators)
    - image: coelho-realtime-kafka-producers
      context: ./apps/kafka-producers
      docker:
        dockerfile: Dockerfile.kafka-producers
      sync:
        manual:
          - src: "**/*.py"
            dest: /app
    # FastAPI (unified ML backend - includes River incremental and Sklearn batch training)
    - image: coelho-realtime-fastapi
      context: ./apps/fastapi
      docker:
        dockerfile: Dockerfile.fastapi
      sync:
        manual:
          - src: "**/*.py"
            dest: /app
    # SvelteKit (primary frontend)
    - image: coelho-realtime-sveltekit
      context: ./apps/sveltekit
      docker:
        dockerfile: Dockerfile.sveltekit
      sync:
        manual:
          - src: "**/*.svelte"
            dest: /app
          - src: "**/*.ts"
            dest: /app
          - src: "**/*.js"
            dest: /app
          - src: "**/*.json"
            dest: /app
          - src: "**/*.css"
            dest: /app
  local:
    push: true  # Push to localhost:5000, K3d registry mirrors handle the rest
    useBuildkit: true
    useDockerCLI: true

# MANIFESTS at top level (v4beta13 structure)
manifests:
  helm:
    releases:
      - name: coelho-realtime
        chartPath: ./k3d/helm
        namespace: coelho-realtime
        createNamespace: true
        skipBuildDependencies: true  # Dependencies committed to repo - see docs/helm_dependencies.md
        setValueTemplates:
          kafka-producers.image: "{{.IMAGE_NAME_coelho_realtime_kafka_producers}}:{{.IMAGE_TAG_coelho_realtime_kafka_producers}}"
          fastapi.image: "{{.IMAGE_NAME_coelho_realtime_fastapi}}:{{.IMAGE_TAG_coelho_realtime_fastapi}}"
          sveltekit.image: "{{.IMAGE_NAME_coelho_realtime_sveltekit}}:{{.IMAGE_TAG_coelho_realtime_sveltekit}}"

deploy:
  helm: {}

portForward:
  # MLFlow
  - resourceType: service
    resourceName: coelho-realtime-mlflow
    namespace: coelho-realtime
    port: 5000
    localPort: 5001
    address: 0.0.0.0
  # MinIO S3 API
  - resourceType: service
    resourceName: coelho-realtime-minio
    namespace: coelho-realtime
    port: 9000
    localPort: 9000
    address: 0.0.0.0
  # MinIO Console (Web UI)
  - resourceType: service
    resourceName: coelho-realtime-minio-console
    namespace: coelho-realtime
    port: 9001
    localPort: 9001
    address: 0.0.0.0
  # Kafka
  - resourceType: service
    resourceName: coelho-realtime-kafka
    namespace: coelho-realtime
    port: 9092
    localPort: 9092
    address: 0.0.0.0
  # FastAPI (unified ML backend)
  - resourceType: service
    resourceName: coelho-realtime-fastapi
    namespace: coelho-realtime
    port: 8000
    localPort: 8000
    address: 0.0.0.0
  # SvelteKit (primary frontend)
  - resourceType: service
    resourceName: coelho-realtime-sveltekit
    namespace: coelho-realtime
    port: 5173
    localPort: 5173
    address: 0.0.0.0
  # Prometheus (service name truncated by Helm)
  - resourceType: service
    resourceName: coelho-realtime-kube-prome-prometheus
    namespace: coelho-realtime
    port: 9090
    localPort: 9090
    address: 0.0.0.0
  # Grafana
  - resourceType: service
    resourceName: coelho-realtime-grafana
    namespace: coelho-realtime
    port: 3000
    localPort: 3000
    address: 0.0.0.0
  # Alertmanager (port 9094 to avoid conflict with Kafka controller, name truncated)
  - resourceType: service
    resourceName: coelho-realtime-kube-prome-alertmanager
    namespace: coelho-realtime
    port: 9094
    localPort: 9094
    address: 0.0.0.0
  # Spark Master Web UI (shows running applications, workers, streaming jobs)
  - resourceType: service
    resourceName: coelho-realtime-spark-master-svc
    namespace: coelho-realtime
    port: 80
    localPort: 4040
    address: 0.0.0.0


profiles:
  # Development profile - Real-time everything
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        # Kafka Producers - Manual sync for hot-reload
        - image: coelho-realtime-kafka-producers
          context: ./apps/kafka-producers
          docker:
            dockerfile: Dockerfile.kafka-producers
          sync:
            manual:
              - src: "**/*.py"
                dest: /app
        # FastAPI (unified ML backend)
        - image: coelho-realtime-fastapi
          context: ./apps/fastapi
          docker:
            dockerfile: Dockerfile.fastapi
          sync:
            manual:
              - src: "**/*.py"
                dest: /app
        # SvelteKit (primary frontend)
        - image: coelho-realtime-sveltekit
          context: ./apps/sveltekit
          docker:
            dockerfile: Dockerfile.sveltekit
          sync:
            manual:
              - src: "**/*.svelte"
                dest: /app
              - src: "**/*.ts"
                dest: /app
              - src: "**/*.js"
                dest: /app
              - src: "**/*.json"
                dest: /app
              - src: "**/*.css"
                dest: /app
    # Profile-specific manifests override (if needed)
    manifests:
      helm:
        releases:
          - name: coelho-realtime
            chartPath: ./k3d/helm
            namespace: coelho-realtime
            createNamespace: true
            skipBuildDependencies: true  # Dependencies committed to repo - see docs/helm_dependencies.md
            setValueTemplates:
              kafka-producers.image: "{{.IMAGE_NAME_coelho_realtime_kafka_producers}}:{{.IMAGE_TAG_coelho_realtime_kafka_producers}}"
              fastapi.image: "{{.IMAGE_NAME_coelho_realtime_fastapi}}:{{.IMAGE_TAG_coelho_realtime_fastapi}}"
              sveltekit.image: "{{.IMAGE_NAME_coelho_realtime_sveltekit}}:{{.IMAGE_TAG_coelho_realtime_sveltekit}}"
    deploy:
      helm: {}

# NOTE: When useBuildkit is set to true (line 58), docker-buildx must be installed.
# Install it via your package manager (e.g., `sudo pacman -S docker-buildx` on Arch Linux).

# DON'T USE MULTI-STAGE DOCKER BUILD - Skaffold won't work fine, will always rebuild images every code change
# sh mirror_localhost_tailscale.sh 7443 5001 5173 9000 9001 8000 9090 3000 9094 9092 4040
