apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: coelho-realtime

build:
  artifacts:
    # NOTE: FastAPI service (port 8001) has been terminated and merged into river/sklearn services
    # Kafka Producers (Python data generators)
    - image: coelho-realtime-kafka-producers
      context: ./apps/kafka-producers
      docker:
        dockerfile: Dockerfile.kafka-producers
      sync:
        manual:
          - src: "**/*.py"
            dest: /app
    # Reflex service (single-stage Dockerfile for proper sync)
    - image: coelho-realtime-reflex
      context: ./apps/reflex
      docker:
        dockerfile: Dockerfile.reflex
        noCache: false
      sync:
        manual:
          - src: "**/*.py"
            dest: /app
          - src: "**/*.json"
            dest: /app
    # River ML Training service
    - image: coelho-realtime-river
      context: ./apps/river
      docker:
        dockerfile: Dockerfile.river
      sync:
        manual:
          - src: "**/*.py"
            dest: /app
    # Sklearn Batch ML service
    - image: coelho-realtime-sklearn
      context: ./apps/sklearn
      docker:
        dockerfile: Dockerfile.sklearn
      sync:
        manual:
          - src: "**/*.py"
            dest: /app
    # NOTE: Streamlit has been removed - fully replaced by Reflex
  local:
    push: true  # Push to localhost:5000, K3d registry mirrors handle the rest
    useBuildkit: true
    useDockerCLI: true

# MANIFESTS at top level (v4beta13 structure)
manifests:
  helm:
    releases:
      - name: coelho-realtime
        chartPath: ./k3d/helm
        namespace: coelho-realtime
        createNamespace: true
        skipBuildDependencies: true  # Dependencies committed to repo - see docs/helm_dependencies.md
        setValueTemplates:
          # Skaffold will automatically replace these with built image tags
          # NOTE: fastapi and streamlit services removed - replaced by river/sklearn/reflex
          kafka-producers.image: "{{.IMAGE_NAME_coelho_realtime_kafka_producers}}:{{.IMAGE_TAG_coelho_realtime_kafka_producers}}"
          reflex.image: "{{.IMAGE_NAME_coelho_realtime_reflex}}:{{.IMAGE_TAG_coelho_realtime_reflex}}"
          river.image: "{{.IMAGE_NAME_coelho_realtime_river}}:{{.IMAGE_TAG_coelho_realtime_river}}"
          sklearn.image: "{{.IMAGE_NAME_coelho_realtime_sklearn}}:{{.IMAGE_TAG_coelho_realtime_sklearn}}"

deploy:
  helm: {}

portForward:
  # NOTE: FastAPI service (port 8001) has been terminated and merged into river/sklearn services
  # MLFlow
  - resourceType: service
    resourceName: coelho-realtime-mlflow
    namespace: coelho-realtime
    port: 5000
    localPort: 5001
    address: 0.0.0.0
  # Reflex (frontend)
  - resourceType: service
    resourceName: coelho-realtime-reflex
    namespace: coelho-realtime
    port: 3000
    localPort: 3000
    address: 0.0.0.0
  # Reflex (backend)
  - resourceType: service
    resourceName: coelho-realtime-reflex
    namespace: coelho-realtime
    port: 8000
    localPort: 8000
    address: 0.0.0.0
  # MinIO S3 API
  - resourceType: service
    resourceName: coelho-realtime-minio
    namespace: coelho-realtime
    port: 9000
    localPort: 9000
    address: 0.0.0.0
  # MinIO Console (Web UI)
  - resourceType: service
    resourceName: coelho-realtime-minio-console
    namespace: coelho-realtime
    port: 9001
    localPort: 9001
    address: 0.0.0.0
  # Kafka
  - resourceType: service
    resourceName: coelho-realtime-kafka
    namespace: coelho-realtime
    port: 9092
    localPort: 9092
    address: 0.0.0.0
  # River ML Training
  - resourceType: service
    resourceName: coelho-realtime-river
    namespace: coelho-realtime
    port: 8002
    localPort: 8002
    address: 0.0.0.0
  # Sklearn Batch ML
  - resourceType: service
    resourceName: coelho-realtime-sklearn
    namespace: coelho-realtime
    port: 8003
    localPort: 8003
    address: 0.0.0.0
  # Prometheus (service name truncated by Helm)
  - resourceType: service
    resourceName: coelho-realtime-kube-prome-prometheus
    namespace: coelho-realtime
    port: 9090
    localPort: 9090
    address: 0.0.0.0
  # Grafana (port 3001 to avoid conflict with Reflex)
  - resourceType: service
    resourceName: coelho-realtime-grafana
    namespace: coelho-realtime
    port: 3001
    localPort: 3001
    address: 0.0.0.0
  # Alertmanager (port 9094 to avoid conflict with Kafka controller, name truncated)
  - resourceType: service
    resourceName: coelho-realtime-kube-prome-alertmanager
    namespace: coelho-realtime
    port: 9094
    localPort: 9094
    address: 0.0.0.0
  # Spark Master Web UI (shows running applications, workers, streaming jobs)
  - resourceType: service
    resourceName: coelho-realtime-spark-master-svc
    namespace: coelho-realtime
    port: 80
    localPort: 4040
    address: 0.0.0.0
  # Kafka JMX metrics disabled (JMX exporter incompatible with Kafka 4.0)
  # - resourceType: service
  #   resourceName: coelho-realtime-kafka-jmx-metrics
  #   namespace: coelho-realtime
  #   port: 5556
  #   localPort: 5556
  #   address: 0.0.0.0
  # NOTE: Streamlit removed - fully replaced by Reflex


profiles:
  # Development profile - Real-time everything
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        # NOTE: FastAPI service has been terminated and merged into river/sklearn services
        # Kafka Producers - Manual sync for hot-reload
        - image: coelho-realtime-kafka-producers
          context: ./apps/kafka-producers
          docker:
            dockerfile: Dockerfile.kafka-producers
          sync:
            manual:
              - src: "**/*.py"
                dest: /app
        # Reflex - Single-stage Dockerfile for proper file sync
        - image: coelho-realtime-reflex
          context: ./apps/reflex
          docker:
            dockerfile: Dockerfile.reflex
            noCache: false
          sync:
            manual:
              - src: "**/*.py"
                dest: /app
              - src: "**/*.json"
                dest: /app
        # River ML Training - Manual sync for hot-reload
        - image: coelho-realtime-river
          context: ./apps/river
          docker:
            dockerfile: Dockerfile.river
          sync:
            manual:
              - src: "**/*.py"
                dest: /app
        # Sklearn Batch ML - Manual sync for hot-reload
        - image: coelho-realtime-sklearn
          context: ./apps/sklearn
          docker:
            dockerfile: Dockerfile.sklearn
          sync:
            manual:
              - src: "**/*.py"
                dest: /app
        # NOTE: Streamlit has been removed - fully replaced by Reflex
    # Profile-specific manifests override (if needed)
    manifests:
      helm:
        releases:
          - name: coelho-realtime
            chartPath: ./k3d/helm
            namespace: coelho-realtime
            createNamespace: true
            skipBuildDependencies: true  # Dependencies committed to repo - see docs/helm_dependencies.md
            setValueTemplates:
              # NOTE: fastapi and streamlit removed - replaced by river/sklearn/reflex
              kafka-producers.image: "{{.IMAGE_NAME_coelho_realtime_kafka_producers}}:{{.IMAGE_TAG_coelho_realtime_kafka_producers}}"
              reflex.image: "{{.IMAGE_NAME_coelho_realtime_reflex}}:{{.IMAGE_TAG_coelho_realtime_reflex}}"
              river.image: "{{.IMAGE_NAME_coelho_realtime_river}}:{{.IMAGE_TAG_coelho_realtime_river}}"
              sklearn.image: "{{.IMAGE_NAME_coelho_realtime_sklearn}}:{{.IMAGE_TAG_coelho_realtime_sklearn}}"
    deploy:
      helm: {}

# NOTE: When useBuildkit is set to true (line 58), docker-buildx must be installed.
# Install it via your package manager (e.g., `sudo pacman -S docker-buildx` on Arch Linux).

# DON'T USE MULTI-STAGE DOCKER BUILD - Skaffold won't work fine, will always rebuild images every code change
# sh mirror_localhost_tailscale.sh 5001 3000 8000 9000 9001 8002 8003 9090 3001 9094 9092 4040