FROM python:3.12-slim

# Set the HTTP timeout to 300 seconds (5 minutes)
ENV UV_HTTP_TIMEOUT=300

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates jq

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# Set the working directory
WORKDIR /app

COPY . /app
COPY entrypoint.sh /app/entrypoint.sh

# Make entrypoint executable AFTER copying into the container
RUN chmod +x /app/entrypoint.sh

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run the app
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]