FROM python:3.12-slim

COPY . /app
# Set the working directory
WORKDIR /app

RUN pip install uv --no-cache-dir

# Expose port 8501 for Streamlit
EXPOSE 8501

# Run the app
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]