FROM python:3.13.3-alpine3.21 AS builder 

ENV PYTHONOPTIMIZE=2 \ 
    PYTHONDONTWRITE8YTECODE=1 

COPY pyproject.toml ./ 
RUN pip install uv && uv pip install --system -r pyproject.toml 

###################################################

FROM python:3.13.3-alpine3.21 

ENV PYTHONUNBUFFERED=1 \ 
    APP_PATH="/opt"

WORKDIR $APP_PATH 

COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages 
COPY --from=builder /usr/local/bin/uvicorn /usr/local/bin/uvtcorn 
COPY app app 
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

