FROM python:3.13-slim

COPY . /app

WORKDIR /app

RUN apt-get update && apt-get install -y procps && \
    pip install uv --no-cache-dir

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run the app
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]